### ISSUE TITLE
Update the homepage with Volunteer Section

### ISSUE THREAD

**Issue by DivvSaxena** [FOSS-Community/fossconf#14]
Working on this to add this feature.

**Comment by DivvSaxena** [comment]
Working on it!

**Comment by vivekpal1** [comment]
@DivvSaxena Assigned you for this
If the list seems so large, adjust the picture sizes,
or there is a separate page for organisers https://conference.fosscu.org/organisers/ , so you can remove it from home 
ping me on discord for any doubt

**Comment by vivekpal1** [comment]
PR #15 by @DivvSaxena fixes this issue
